//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerXtreme
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Customer
    {
        //[Required(ErrorMessage = "Please enter code")]
        [Remote("IsCodeValid","Home", ErrorMessage = "Code must be unique")]
        public string code { get; set; }

        [Required(ErrorMessage = "Please enter name")]
        public string name { get; set; }

        [Required(ErrorMessage = "Please enter password")]
        public string password { get; set; }

        [ValidationAge]
        public Nullable<System.DateTime> dob { get; set; }

        [RegularExpression(@"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}", ErrorMessage = "Please enter valid Email address")]
        public string email { get; set; }

        [MaxLength(10, ErrorMessage = "Contact number must be 10 digit")]
        public string phone { get; set; }
    }
}
